/*
 * This source file was generated by the Gradle 'init' task
 */
package com.wuzhenben.diceytemperatures;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GuessTheSumTest {
    @Test void appHasAGreeting() {
        GuessTheSum classUnderTest = new GuessTheSum();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
